services:
  memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: memgraph
    ports:
      - "7687:7687"
      - "7444:7444"
    environment:
      - MGCONSOLE=--username memgraph --password memgraph
    command: ["--schema-info-enabled=True"]
    volumes:
      - memgraph-data:/var/lib/memgraph
    stop_grace_period: 60s
    restart: unless-stopped

  memgraph_lab:
    image: memgraph/lab:latest
    container_name: memgraph_lab
    ports:
      - "3000:3000"
    environment:
      QUICK_CONNECT_MG_HOST: memgraph
    depends_on:
      - memgraph
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__STORAGE__STORAGE_PATH=/qdrant/storage
      - QDRANT__LOGGING__LEVEL=INFO
    restart: unless-stopped
volumes:
  memgraph-data:
  qdrant_storage:
